FROM ubuntu:22.04 as base

RUN set -eux; \
    apt update && apt upgrade -y && \
    apt install -y libnuma-dev openssl libcurl4-openssl-dev binutils-dev libssl-dev \
        libgmp-dev libmpfr-dev libmpc-dev libisl-dev \
        make automake autoconf ninja-build cmake gperf \
        flex bison gcc-12 g++-12 \
        python3 python3-pip python3-dev openjdk-17-jdk \
        vim git git-lfs openssh-client ssh wget bzip2 && \
    ln -sf /usr/bin/gcc-12 /usr/local/bin/gcc && \
    ln -sf /usr/bin/g++-12 /usr/local/bin/g++ && \
    mkdir -p /usr/lib/jvm && \
    ln -sfn "$(dirname "$(dirname "$(readlink -f "$(command -v javac)")")")" /usr/lib/jvm/java-17-openjdk

ARG BUILD_DIR=/tmp/build
ARG CMAKE_VERSION=3.31.10
ARG MAVEN_VERSION=3.9.12

# Install CMake
RUN mkdir -p ${BUILD_DIR} && \
    cd ${BUILD_DIR} && \
    wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz && \
    tar xf cmake-${CMAKE_VERSION}.tar.gz && \
    cd cmake-${CMAKE_VERSION} && \
    ./bootstrap --parallel=$(nproc) && \
    ./configure --prefix=/usr && \
    make -j$(nproc) && \
    make install && \
    cmake --version && \
    rm -rf ${BUILD_DIR}/*

ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk
ENV PATH "$JAVA_HOME/bin:$PATH"

# Install maven
ARG MAVEN_DIR=/opt/maven/apache-maven-${MAVEN_VERSION}
ARG MAVEN_URL=https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
RUN mkdir -p ${MAVEN_DIR} && \
    wget -qO- ${MAVEN_URL} | tar -zxf - -C  ${MAVEN_DIR} --strip-components=1 && \
    ln -sf ${MAVEN_DIR}/bin/mvn /usr/bin/mvn
ENV MAVEN_HOME ${MAVEN_DIR}
ENV PATH ${MAVEN_HOME}/bin:${PATH}

# Install Conda & Conan
RUN MINICONDA_VERSION=py310_23.1.0-1 && \
    MINICONDA_URL=https://repo.anaconda.com/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-$(arch).sh && \
    mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR} && \
    wget --progress=dot:mega -O miniconda.sh ${MINICONDA_URL} && \
    chmod +x miniconda.sh && \
    ./miniconda.sh -b -u -p /root/miniconda3 && rm -f miniconda.sh && \
    echo "export PATH=/root/miniconda3/bin:\$PATH" >> /root/.bashrc && . /root/.bashrc && \
    pip install --upgrade pip || true && \
    pip install pydot conan && \
    conan profile detect
ENV PATH "/root/miniconda3/bin:${PATH}"

# Install Python test dependencies required by Spark UTs (pyspark-driven tests).
RUN PIP_PROGRESS_BAR=off pip install --disable-pip-version-check \
    pyspark==3.5.5 cython pandas==2.2.3 pyarrow==20.0.0

COPY .github/workflows/util/install-spark-resources.sh /usr/local/bin/install-spark-resources.sh
RUN chmod +x /usr/local/bin/install-spark-resources.sh && \
    /usr/local/bin/install-spark-resources.sh 3.5 /opt/

RUN apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/build
